name: Build RPM

on:
  workflow_dispatch:

jobs:
  rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Install dependencies
        run: |
          dnf install -y java-21-openjdk-devel maven rpm-build


      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build project with Maven
        run: mvn clean install -Dgit.commit.id.skip=true

      - name: Create RPM build structure
        run: |
          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp packaging/oscal-cli.spec rpmbuild/SPECS/
          tar -czf rpmbuild/SOURCES/oscal-cli.tar.gz --transform "s/^./oscal-cli/" .

      - name: Build the RPM
        run: |
          rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba rpmbuild/SPECS/oscal-cli.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: oscal-cli-rpm
          path: rpmbuild/RPMS/**/*.rpm
