name: Build RPM

on:
  workflow_dispatch:

jobs:
  rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build project with Maven
        run: mvn clean install

      - name: Install rpmbuild
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Create RPM build structure
        run: |
          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp packaging/oscal-cli.spec rpmbuild/SPECS/
          tar -czf rpmbuild/SOURCES/oscal-cli.tar.gz --transform "s/^./oscal-cli/" .

      - name: Build the RPM
        run: |
          rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba rpmbuild/SPECS/oscal-cli.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: oscal-cli-rpm
          path: rpmbuild/RPMS/**/*.rpm
